mri.script <- function(script.dir, script.name,
                       user.name, project.name, project.description,
                       FUNC, FORM, OPTS = NULL,
                       libraries = c("mRi", "parallel", "lmerTest", "car"),
                       data.4d = NULL,
                       data.mask = NULL,
                       data.paradigm,
                       mri.dir,
                       mri.name,
                       save.dir,
                       prefix,
                       subset = FALSE,
                       center = FALSE,
                       scale = FALSE,
                       decompose = FALSE,
                       t.shift = FALSE,
                       outlier.abs = FALSE,
                       outlier.group = TRUE,
                       outlier.model = TRUE,
                       log.file = NULL) {
  
  # Debug ----
  script.dir <- "C:/Users/MBBHResearch/Dropbox (Personal)/Programs/script.write.test"
  script.name <- "testScript"
  user.name <- "Tim Koscik, PhD"
  project.name <- "Script Generator Test"
  project.description <- "blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah"
  libraries <- c("mRi", "parallel", "lmerTest", "car")
  data.4d <- "C:/Users/MBBHResearch/Documents/Koscik/mri.filetype.test/scans"
  data.mask <- "C:/Users/MBBHResearch/Documents/Koscik/mri.filetype.test/mask.nii"
  mri.dir <- "C:/Users/MBBHResearch/Documents/Koscik/mri.filetype.test"
  mri.name <- "testFile"
  log.file <- NULL
  save.dir <- "C:/Users/MBBHResearch/Documents/Koscik/mri.filetype.test"
  subset <- "df$excl == criteria"
  # ----
  
  # Check file name
  scriptf <- paste0(script.dir, "/", script.name, ".R")
  stopifnot(!file.exists(scriptf))
  
  # initialize script
  fid <- file(scriptf, method = "w+")
  sink(fid)
  
  # Write header information
  cat("# mRi Analysis Script ==================================================================", sep="\n", append = TRUE)
  cat(sprintf("# This script was generated by mRi version %s", packageVersion("mRi")), sep="\n", append = TRUE)
  cat("# Copyright (C) 2017 Koscik, Timothy R. All rights Reserved.", sep="\n", append = TRUE)
  cat("# Address correspondence to <kosciklab@gmail.com>", sep="\n", append = TRUE)
  cat("#", sep="\n", append = TRUE)
  cat(sprintf("# Anaylsis Author:\t\t\t%s", user.name), sep="\n", append = TRUE)
  cat(sprintf("# Script Name:\t\t\t\t\t\t%s.R", script.name), sep="\n", append=TRUE)
  cat(sprintf("# Project Name:\t\t\t\t\t", project.name), sep="\n", append=TRUE)
  cat(sprintf("# Date Created:\t\t\t\t\t%s", date()), sep="\n", append=TRUE)
  cat("# Analysis Description -----------------------------------------------------------------", sep="", append = TRUE)
  for (i in 1:nchar(project.description)) {
    if ((i %% 80) == 1) {
      cat("", sep="\n", append=TRUE)
      cat("# ", sep="", append=TRUE)
    }
    cat(substr(project.description, start = i, stop = i), sep="", append=TRUE)
  }
  cat("", sep="\n", append=TRUE)
  cat("# ======================================================================================", sep="\n", append=TRUE)
  cat("", sep="\n", append=TRUE)
  
  # Write Environment Setup
  cat("# Setup Environment --------------------------------------------------------------------", sep="\n", append=TRUE)
  cat("rm(list=ls())", sep="\n", append=TRUE)
  cat("gc()", sep="\n", append=TRUE)
  for (i in 1:length(libraries)) {
    cat(sprintf("library('%s')", libraries[i]), sep="\n", append=TRUE)
  }
  cat("", sep="\n", append=TRUE)
  
  # Make *.mri file if appropriate inputs given
  if (!is.null(data.4d)) {
    cat("# Make *.mri file if desired ----------------------------------------------------------", sep="\n", append=TRUE)
    cat(sprintf("data.4d <- '%s'", data.4d), sep="\n", append=TRUE)
    cat(sprintf("data.mask <- '%s'", data.mask), sep="\n", append=TRUE)
    cat(sprintf("mri.dir <- '%s'", mri.dir), sep="\n", append=TRUE)
    cat(sprintf("mri.name <- '%s'", mri.name), sep="\n", append=TRUE)
    cat("", sep="\n", append=TRUE)
    cat("# Make mRi study file ------------------------------------------------------------------", sep="\n", append=TRUE)
    cat("mri.make(data.4d, data.paradigm, mri.dir, mri.name)", sep="\n", append=TRUE)
    cat("", sep="\n", append=TRUE)
  }
  
  # Setup analysis
  cat("# Analysis -----------------------------------------------------------------------------", sep="\n", append=TRUE)
  cat("# Timeseries data", sep="\n", append=TRUE)
  cat("mri.file <- paste0(mri.dir, '/', mri.name, '.mri')", sep="\n", append=TRUE)
  cat("mri.info <- mri.hdr(mri.file, 'all')", sep="\n", append=TRUE)
  cat("img.dims <- mri.info$img.dims[2:4]", sep="\n", append=TRUE)
  cat("pixdim <- mri.info$pixdim", sep="/n", append=TRUE)
  cat("orient <- list(qform_code=mri.info$qform_code, sform_code=mri.info$sform_code, quatern_b=mri.info$quatern_b, quatern_c=mri.info$quatern_c, quatern_d=mri.info$quatern_d, qoffset_x=mri.info$qoffset_x, qoffset_y=mri.info$qoffset_y, qoffset_z=mri.info$qoffset_z, srow_x=mri.info$srow_x, srow_y=mri.info$srow_y, srow_z=mri.info$srow_z")
  cat("", sep="\n", append=TRUE)
  
  cat("# paradigm data", sep="\n", append=TRUE)
  cat(sprintf("data.paradigm <- '%s'", data.paradigm), sep="\n", append=TRUE)
  cat("pf <- parse.paradigm(data.paradigm)", sep="\n", append=TRUE)
  cat("", sep="\n", append=TRUE)
  
  # cat("# load mask", sep="\n", append=TRUE)
  # cat("which.voxels <- load.mask(data.mask)", sep="\n", append=TRUE)
  # cat("n.masks <- length(which.voxels)", sep="\n", append=TRUE)
  # cat("", sep="\n", append=TRUE)
  
  cat("# Initialize Log File", sep="\n", append=TRUE)
  if (is.null(log.file)) {
    cat(sprintf("log.file <- '%s/log.nii'", save.dir), sep="\n", append=TRUE)
  }
  cat(sprintf("init.nii('%s', img.dims, pixdim, orient)", log.file), sep="\n", append=TRUE)
  cat("", sep="\n", append=TRUE)
  
  cat("# Analysis function", sep="\n", append=TRUE)
  cat("my.function <- function(X, ...) {", sep="\n", append=TRUE)
  cat("\t# Check Log File (continue only if not run)", sep="\n", append=TRUE)
  cat("\tchk.vx <- read.nii.voxel(log.file, which.voxels[X, ])", sep="\n", append=TRUE)
  cat("\tif (!chk.vx) {", sep="\n", append=TRUE)  
  
  cat("\t\t# combine timeseries and paradigm data into a single dataframe", sep="\n", append=TRUE)
  cat("\t\tif (!is.null(data.mri)) {", sep="\n", append=TRUE)
  cat("\t\t\ttf <- mri.load(mri.file, X)", sep="\n", append=TRUE)
  cat("\t\t\tdf <- data.frame(tf$fmri, pf)", sep="\n", append=TRUE)
  cat("\t\t} else {", sep="\n", append=TRUE)
  cat("\t\t\tdf <- pf", sep="\n", append=TRUE)
  cat("\t\t}", sep="\n", append=TRUE)
  cat("", sep="\n", append=TRUE)
  
  #****
  if (!is.logical(subset)) {
    cat("# Exclude rows from dataset", sep="\n", append=TRUE)
    cat(sprintf("df <- df[%s, ]", subset), sep="\n", append=TRUE)
    cat("", sep="\n", append=TRUE)
  }
  
  if (is.logical(outlier.abs)) {
    if (outlier.abs) {
      cat("# Remove outliers by absolute value", sep="\n", append=TRUE)
      cat("ex <- which(abs(df$fmri) > 3)", sep="\n", append=TRUE)
      cat("df <- df[ex, ]", sep="\n", append=TRUE)
      cat("out.rm.abs.fmri <- matrix(c(length(ex), length(ex)/nrow(df)), ncol = 1, dimnames = list(c('N', 'pct'), c('abs')))", sep="\n", append=TRUE)
      cat("table.to.nii(out.rm.abs.fmri, tf$coords, tf$img.dims, save.dir, prefix, pixdim=tf$pixdim, orient=tf$orient)", sep="\n", append=TRUE)
      cat("", sep="\n", append=TRUE)
    }
  } else {
    cat("# Remove outliers by absolute value", sep="\n", append=TRUE)
    for (i in 1:length(outlier.abs)) {
      cat(paste0("ex <- which(abs(df$", outlier.abs[[i]]$var.name, ") > ", outlier.abs[[i]]$cutoff, ")"), sep="\n", append=TRUE)
      cat("df <- df[ex, ]", sep="\n", append=TRUE)
      cat(paste0("out.rm.abs.", outlier.abs[[i]]$var.name, " <- matrix(c(length(ex), length(ex)/nrow(df)), ncol = 1, dimnames = list(c('N', 'pct'), c('abs')))"), sep="\n", append=TRUE)
      cat(paste0("table.to.nii(out.rm.abs", outlier.abs[[i]]$var.name, ", tf$coords, tf$img.dims, save.dir, prefix, pixdim=tf$pixdim, orient=tf$orient)"), sep="\n", append=TRUE)
      cat("", sep="\n", append=TRUE)
    }
  }
  
  if (is.logical(outlier.group)) {
    if (outlier.group) {
      cat("# Remove outliers by deviation from group-level mean", sep="\n", append=TRUE)
      cat("ex <- outliers.by.subject(df, 'fmri', 'subject', 3)", sep="\n", append=TRUE)
      cat("out.rm.group.fmri <- matrix(c(ex$n.removed, ex$percent.removed), ncol = 1, dimnames = list(c('N', 'pct'), c('group')))", sep="\n", append=TRUE)
      cat("table.to.nii(out.rm.group.fmri, tf$coords, tf$img.dims, save.dir, prefix, pixdim=tf$pixdim, orient=tf$orient)", sep="\n", append=TRUE)
      cat("df <- ex$data", sep="\n", append=TRUE)
      cat("", sep="\n", append=TRUE)
    }
  } else {
    cat("# Remove outliers by deviation from group-level mean", sep="\n", append=TRUE)
    for (i in 1:length(outlier.group)) {
      cat(paste0("ex <- outliers.by.subject(df, '", outlier.group[[i]]$var.name, "', '", outlier.group[[i]]$group, "', ", outlier.group$cutoff, ")"), sep="\n", append=TRUE)
      cat(paste0("out.rm.group.", outlier.group[[i]]$var.name, ".", outlier.group[[i]]$group, " <- matrix(c(ex$n.removed, ex$percent.removed), ncol = 1, dimnames = list(c('N', 'pct'), c('group')))"), sep="\n", append=TRUE)
      cat(paste0("table.to.nii(out.rm.group.", outlier.group[[i]]$var.name, ".", outlier.group[[i]]$group, ", tf$coords, tf$img.dims, save.dir, prefix, pixdim=tf$pixdim, orient=tf$orient)"), sep="\n", append=TRUE)
      cat("df <- ex$data", sep="\n", append=TRUE)
      cat("", sep="\n", append=TRUE)
    }
  }
  
  if (!is.logical(center)) {
    cat("# Center variables", sep="\n", append=TRUE)
    for (i in 1:length(center)) {
      if (length(center[[i]] == 1)) {
        cat(paste0("df$", center[[i]]$var.name, " <- df$", center[[i]]$var.name, " - mean(df$", center[[i]]$var.name, ", na.rm=TRUE)"), sep="\n", append=TRUE)
      } else {
        cat(paste0("df$", center[[i]]$var.name, " <- df$", center[[i]]$var.name, " - ", center[[i]]$value), sep="\n", append=TRUE)
      }
    }
    cat("", sep="\n", append=TRUE)
  }
  
  if (!is.logical(scale)) {
    cat(" Scale variables", sep="\n", append=TRUE)
    for (i in 1:length(center)) {
      if (length(scale[[i]] == 1)) {
        cat(paste0("df$", scale[[i]]$var.name, " <- df$", scale[[i]]$var.name, " / sd(df$", scale[[i]]$var.name, ")"), sep="\n", append=TRUE)
      } else {
        cat(paste0("df$", scale[[i]]$var.name, " <- df$", scale[[i]]$var.name, " / ", scale[[i]]$value), sep="\n", append=TRUE)
      }
    }
    cat("", sep="\n", append=TRUE)
  }
  
  #
  
  
  cat("\t}", sep="\n", append=TRUE)
  cat("}", sep="\n", append=TRUE)
  cat("", sep="\n", append=TRUE)
  
  
  
  
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  cat(, sep="\n", append=TRUE)
  
  close(fid)
}

